import "./globals.css";
import { cx } from "@/utils"
import Header from "@/components/Header";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cx(GeistSans.className, GeistMono.className, "antialiased bg-white dark:bg-dark")}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
