import "./globals.css";
import { cx } from "@/utils"
import Header from "@/components/Header";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import Footer from "@/components/Footer";


export const metadata = {
  title: "Yylime's Blog",
  description: "Generated by yylime",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cx(GeistSans.className, GeistMono.className, "antialiased bg-white dark:bg-dark")}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
